name: Pytest with Coverage

on:
  push:
    branches:
      - main      
  pull_request:
    branches:
      - main       
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage

      - name: Run pytest with coverage
        run: |
          coverage run --branch -m pytest
          coverage xml        # creates coverage.xml with per-file, per-line data
          coverage html       # creates htmlcov/ for human-friendly view
          coverage report     # plain text summary in logs
          
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov

      - name: Upload XML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
